version: "3.3"

services:

    #chat-app:
    #    build:
    #        context: ./app
    #        dockerfile: Dockerfile

    #    ports:
    #        - "8084:80"

    #    volumes:
    #        - ./app:/var/www/html/app

    socket:
        build:
            context: ./socket
            dockerfile: Dockerfile

        ports:
            - "9980:9980"

        volumes:
            - ./socket:/var/www/html/app
